name: Build translations

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed

    steps:
    - name: Install dependencies
      run: zypper install -y tar gawk gzip ruby-devel "rubygem(bundler)" gcc-c++ gettext-tools make zlib-devel git-core libxml2-devel libxslt-devel libffi-devel

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: BUNDLE_PATH=.bundle bundle install -j=4

    - name: Build the site
      run: BUNDLE_PATH=.bundle LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=C.UTF-8 bundle exec jekyll build

    - name: Run the script
      run: BUNDLE_PATH=.bundle LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=C.UTF-8 bundle exec ruby po/update_po.rb

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Submit built translations
        file_pattern: assets/js/langpack/* po/*.pot
